name: Deploy

on:
  push:
    branches:
      - master

env:
  JAVA_VERSION: '11.0.5'
  DEPS_VERSION: '1.10.1.469'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Deploy
        env:
          DEPLOY_TARGET_SSH: ${{ secrets.DEPLOY_TARGET_SSH }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: bin/deploy
